### ISSUE TITLE
Detecting Anomaly

### ISSUE THREAD

**Issue by imurs34** [xyjprc/hon#5]
Hi, thank you for your wonderful project!
I've got a question on detecting anomaly, so how can I use the output to detect anomaly in my data? Is there any code that I can measure the distances?

Again, thank you for sharing your great work!

**Comment by xyjprc** [comment]
Hi @imurs34, thank you for your interest in our project!

Regarding anomaly detection, I had uploaded [slides](https://github.com/xyjprc/hon/blob/master/papers/HON-Anomaly_KDD_ADF.pdf) and [paper](https://github.com/xyjprc/hon/blob/master/papers/AnomalyDetectionUsingHON.pdf) to the repo, detailing applications on how to use HON for specific types of anomalies.

Note that HON itself is not meant to be an anomaly detection algorithm; what was illustrated in the paper is that there are certain types of anomalies (change-points, or sophisticated attacks, whichever way you see it) that, once represented as the first-order network, can no longer be detected using standard anomaly detection algorithms for dynamic networks. 

You can choose any distance metric you want. Equation (1) is the most commonly used weight distance. I have uploaded an old snippet of the implementation of graph diff for your reference [link](https://github.com/xyjprc/hon/blob/master/pyHON/graph-diff.py). The code was written a couple of years ago (read: bad implementation) and has hard-coded paths (read: you need to update). Still, hope it can be helpful. Mandana Saebi @msaebi has implemented other distance measures in a recent revision.

A better way to handle graph operations is using packages like NetworkX, which has many functions built-in. [Link](https://networkx.github.io/documentation/stable/reference/algorithms/index.html?highlight=maximum%20common%20subgraph)

Let us know if this answers your question.

**Comment by imurs34** [comment]
Oh, thank you for your kind and prompt reply! The code you provided is really helpful! NetworkX seems powerful and relevant to my project as well. I'll come back if I need additional explanation in implementing your code, I cannot thank you enough! I'm very impressed by your continuous effort to make your project more accessible and available to more people.

Thanks agian :)!
